# 服务名称
spring:
  application:
    name: hengboy-spring-cloud-eureka-high-provider

# 端口号
server:
  port: 20000

# Eureka集群配置信息
eureka:
  client:
    service-url:
      defaultZone: http://node1:10001/eureka/,http://node2:10002/eureka/