# service instance name
spring:
  application:
    name: hengboy-sca-nacos-discovery-consumer-feign
  # nacos discovery config
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
server:
  port: 9100
